### ISSUE TITLE
Update problem 'All previous versions' cannot be processed

### ISSUE THREAD

**Issue by molu8bits** [cyberaz0r/badmoodle#2]
Nice script. Founds properly vulnerabilities on some testing older 3.9 Moodle instance.

Anyway when I use "--update" it shows an exception. Seems like string 'All previous versions' cannot be processed.

```
[+] Moodle version: v3.9

[*] Checking for official vulnerabilities from vulnerability database
Traceback (most recent call last):
  File "./badmoodle.py", line 235, in <module>
    main()
  File "./badmoodle.py", line 228, in main
    check_official_vulnerabilities(version)
  File "./badmoodle.py", line 86, in check_official_vulnerabilities
    vulnerabilities_found = list_vulnerabilities(version[1:].split('-')[0])
  File "/root/badmoodle/utils/version.py", line 76, in list_vulnerabilities
    if check_in_range(ver, vuln_ver):
  File "/root/badmoodle/utils/version.py", line 61, in check_in_range
    ver_from = int(''.join([str(x).zfill(2) for x in vuln_ver['from'].split('.')]))
ValueError: invalid literal for int() with base 10: 'All previous versions'


```

**Comment by cyberaz0r** [comment]
Hi, thank you for reporting this issue, now with the latest commit it should be fixed
